version: '3.8'

services:
  hanzo-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: hanzo-build:latest
    container_name: hanzo-build-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Database
      - DATABASE_URL=${DATABASE_URL}
      # Redis
      - REDIS_URL=${REDIS_URL}
      # Auth
      - HF_CLIENT_ID=${HF_CLIENT_ID}
      - HF_CLIENT_SECRET=${HF_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://hanzo.app
      # Stripe
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRO_MONTHLY_PRICE_ID=${STRIPE_PRO_MONTHLY_PRICE_ID}
      - STRIPE_PRO_YEARLY_PRICE_ID=${STRIPE_PRO_YEARLY_PRICE_ID}
      # AI Providers
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      # Storage
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - hanzo-network
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=hanzo-network"
      # HTTP Router
      - "traefik.http.routers.hanzo-build.rule=Host(`hanzo.app`)"
      - "traefik.http.routers.hanzo-build.entrypoints=web"
      - "traefik.http.routers.hanzo-build.middlewares=hanzo-build-redirect"
      # HTTPS Router
      - "traefik.http.routers.hanzo-build-secure.rule=Host(`hanzo.app`)"
      - "traefik.http.routers.hanzo-build-secure.entrypoints=websecure"
      - "traefik.http.routers.hanzo-build-secure.tls=true"
      - "traefik.http.routers.hanzo-build-secure.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.hanzo-build.loadbalancer.server.port=3000"
      # Redirect HTTP to HTTPS
      - "traefik.http.middlewares.hanzo-build-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.hanzo-build-redirect.redirectscheme.permanent=true"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  hanzo-network:
    external: true