version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: unless-stopped
    # No ports exposed - Traefik handles routing via network
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # MongoDB connection with retry logic
      - MONGODB_URI=mongodb://hanzo:${MONGO_PASSWORD:-hanzo_secure_pass_2024}@mongodb:27017/hanzo_build?authSource=admin&retryWrites=true&w=majority
      # Auth
      - HF_CLIENT_ID=${HF_CLIENT_ID}
      - HF_CLIENT_SECRET=${HF_CLIENT_SECRET}
      - HF_TOKEN=${HF_TOKEN}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-default_secret_for_production}
      - NEXTAUTH_URL=https://hanzo.app
      # AI Providers (optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
      - SAMBANOVA_API_KEY=${SAMBANOVA_API_KEY}
      - NOVITA_API_KEY=${NOVITA_API_KEY}
      - HYPERBOLIC_API_KEY=${HYPERBOLIC_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - hanzo-network
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=hanzo-network"
      # HTTP Router
      - "traefik.http.routers.hanzo-build.rule=Host(`hanzo.app`)"
      - "traefik.http.routers.hanzo-build.entrypoints=web"
      - "traefik.http.routers.hanzo-build.middlewares=hanzo-build-redirect"
      # HTTPS Router
      - "traefik.http.routers.hanzo-build-secure.rule=Host(`hanzo.app`)"
      - "traefik.http.routers.hanzo-build-secure.entrypoints=websecure"
      - "traefik.http.routers.hanzo-build-secure.tls=true"
      - "traefik.http.routers.hanzo-build-secure.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.hanzo-build.loadbalancer.server.port=3000"
      # Redirect HTTP to HTTPS
      - "traefik.http.middlewares.hanzo-build-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.hanzo-build-redirect.redirectscheme.permanent=true"
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"http\").get(\"http://localhost:3000/api/health\", (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on(\"error\", () => { process.exit(1); });' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hanzo
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-hanzo_secure_pass_2024}
      - MONGO_INITDB_DATABASE=hanzo_build
    volumes:
      - mongodb_data:/data/db
    networks:
      - hanzo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:
    driver: local

networks:
  hanzo-network:
    external: true