default_platform(:mac)

platform :mac do

  lane :release do
    Dir.chdir("..") do
      sh("bun", "bump")
    end

    version = get_version_number(xcodeproj: "./macos/hanzo.xcodeproj")

    path = "/Users/z/work/hanzo/app/"
    appFileName = path + "Hanzo.app"
    zipFileName = path + "releases/" + version + ".zip"
    
    gym(
      scheme: "release",
      configuration: "Release",
      clean: true,
      workspace: "./macos/hanzo.xcworkspace",
      output_directory: path,
      export_method: "developer-id"
    )

    notarize(
      package: appFileName,
      bundle_id: "com.hanzo.app",
      username: "support@hanzo.ai",
      asc_provider: "HANZO_TEAM_ID"
    )

    zip(
      path: appFileName,
      output_path: zipFileName,
      symlinks: true
    )

    set_github_release(
      repository_name: "hanzoai/app",
      api_token: ENV["GITHUB_API_TOKEN"],
      name: "v" + version,
      tag_name: version,
      description: "No release notes provided.",
      upload_assets: [zipFileName]
    )

    file_url = "https://github.com/hanzoai/app/releases/download/" + version + "/" + version + ".zip"
    
    
    Dir.chdir("..") do
      sh("bun", "appcast")

      sh("./scripts/appcast.sh", file_url, version)

      Dir.glob("#{path}releases/*.zip").each { |file| File.delete(file) }

      sh("git", "add", ".")
      sh("git", "commit", "-m", version)
      sh("git", "push")
    end

    sh("cp", "-R", appFileName, "/Applications/")

    sh("open", "/Applications/Hanzo.app")

    sh("pingme", "Hanzo " + version + " released")
  end
end
