/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Main documentation sidebar
  tutorialSidebar: [
    'README',
    'getting-started',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/frontend',
        'architecture/backend',
        'architecture/services',
      ],
    },
    {
      type: 'category',
      label: 'MCP Integration',
      collapsed: false,
      items: [
        'mcp/overview',
        'mcp/tools',
        'mcp/configuration',
        'mcp/claude-desktop',
      ],
    },
    {
      type: 'category',
      label: 'LLM Router',
      collapsed: false,
      items: [
        'llm-router/overview',
        'llm-router/configuration',
        'llm-router/providers',
        'llm-router/local-models',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/sol-launcher',
        'features/ai-chat',
        'features/file-search',
        'features/window-management',
        'features/clipboard-history',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/index',
        'api/tauri-commands',
        'api/mcp-tools',
        'api/ai-service',
        {
          type: 'autogenerated',
          dirName: 'api/generated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/adding-providers',
        'guides/custom-mcp-tools',
        'guides/local-ai-setup',
        'guides/keyboard-shortcuts',
        'guides/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/setup',
        'development/architecture',
        'development/testing',
        'development/debugging',
        'development/contributing',
        'development/release',
      ],
    },
    {
      type: 'category',
      label: 'Migration Guides',
      items: [
        'migration/tauri-v2',
        'migration/mcp-integration',
        'migration/from-zen',
      ],
    },
  ],
};

module.exports = sidebars;